### ISSUE TITLE
How to find your paper?

### ISSUE THREAD

**Issue by TianMingChen** [D-X-Y/GDAS#1]
How to find your paper?

**Comment by D-X-Y** [comment]
You can find the abstract here: http://xuanyidong.com/publication/gradient-based-diff-sampler/ . The full paper should be released with the CVPR 2019 proceeding (http://openaccess.thecvf.com/CVPR2019.py should be available in about one month).
You can also leave an email in this issue, I will send the preliminary version to you~

**Comment by abcilike** [comment]
I need too. Email:570544602@qq.com

**Comment by abcilike** [comment]
Received the paper ! 
Thanks!

**Comment by D-X-Y** [comment]
You are welcome~

**Comment by SuSuXia** [comment]
I need the paper, too.Email:1849862792@qq.com

**Comment by TianMingChen** [comment]
> You can find the abstract here: http://xuanyidong.com/publication/gradient-based-diff-sampler/ . The full paper should be released with the CVPR 2019 proceeding (http://openaccess.thecvf.com/CVPR2019.py should be available in about one month).
> You can also leave an email in this issue, I will send the preliminary version to you~

I also need the paper,could you email to berlinchen@stu.xmu.edu.cn

**Comment by D-X-Y** [comment]
@TianMingChen Just sent the PDF file.

**Comment by TianMingChen** [comment]
> @TianMingChen Just sent the PDF file.

OK,Thank you very much!

**Comment by D-X-Y** [comment]
FYI, I just upload the PDF file on GitHub: https://github.com/D-X-Y/GDAS/blob/master/data/GDAS.pdf
