### ISSUE TITLE
When will you release your code which finds cell structure from scratch?

### ISSUE THREAD

**Issue by Lily002** [D-X-Y/GDAS#13]
Hi! I read that your code which finds cell structure from scratch is under review

When will you release your code?

I look forward to waiting very much! :)

**Comment by D-X-Y** [comment]
Please refer to #2 . For your convenience, the searching codes will be shared upon the acceptance of our following work.

**Comment by D-X-Y** [comment]
Please see the instructions at here https://github.com/D-X-Y/NAS-Projects#searching-on-the-nasnet-search-space
You can use GDAS to search on the DARTS search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/GDAS-search-NASNet-space.sh cifar10 1 -1
```
or on the NAS-bench-102 search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/algos/GDAS.sh     cifar10 -1
```
