### ISSUE TITLE
Must set TORCH_HOME envoriment variable for data dir saving

### ISSUE THREAD

**Issue by zihaozhang9** [D-X-Y/GDAS#15]
I use `UDA_VISIBLE_DEVICES=0 bash ./scripts-cnn/train-cifar.sh GDAS_FG cifar10  cut`,
get `Must set TORCH_HOME envoriment variable for data dir saving`

**Comment by D-X-Y** [comment]
TORCH_HOME must be set to use my scripts, you can set it as '~/.torch', you can simply use `export TORCH_HOME="~/.torch"`.

**Comment by iaxat** [comment]
> TORCH_HOME must be set to use my scripts, you can set it as '~/.torch', you can simply use `export TORCH_HOME="~/.torch"`.

How to do it and where?

**Comment by D-X-Y** [comment]
@iaxat  in bashrc
