### ISSUE TITLE
Ask for  code of searching model?

### ISSUE THREAD

**Issue by Randylcy** [D-X-Y/GDAS#16]
I wanna search model in my own dataset, wish the author to release the code when U R convenient. Best wishes.

**Comment by D-X-Y** [comment]
Thanks for your interest.
Please refer to #2 for the release problem of searching code.
For your convenience, the searching codes will be shared upon the acceptance of our following work.

**Comment by D-X-Y** [comment]
@Randylcy Please find our searching codes here https://github.com/D-X-Y/NAS-Projects#usage-2

**Comment by D-X-Y** [comment]
@Randylcy An update of searching codes:
Detailed instructions at here https://github.com/D-X-Y/NAS-Projects#searching-on-the-nasnet-search-space.
For short, you can use GDAS to search on the DARTS search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/GDAS-search-NASNet-space.sh cifar10 1 -1
```
or on the NAS-bench-102 search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/algos/GDAS.sh     cifar10 -1
```
