### ISSUE TITLE
Training process of searched architecture

### ISSUE THREAD

**Issue by PluviophileYU** [D-X-Y/GDAS#17]
Hi, I read the codes from DARTS firstly and I didn't find the part of training the architecture in your codes, eg: the gumbel trick in your paper. Look forward to your replying!

**Comment by D-X-Y** [comment]
Please refer to #16 and #2 . Thanks for your patience and understanding.

**Comment by D-X-Y** [comment]
@PluviophileYU Sorry for the inconvenience.
Please see the instructions at here https://github.com/D-X-Y/NAS-Projects#searching-on-the-nasnet-search-space
You can use GDAS to search on the DARTS search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/GDAS-search-NASNet-space.sh cifar10 1 -1
```
or on the NAS-bench-102 search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/algos/GDAS.sh     cifar10 -1
```
