### ISSUE TITLE
Can you share the code of the search model?

### ISSUE THREAD

**Issue by SuSuXia** [D-X-Y/GDAS#2]

**Comment by D-X-Y** [comment]
Sorry about that. Since our extension version is under review, we can not release the searching code right now.

**Comment by SuSuXia** [comment]
Thank you, and will this part of the code be shared later?

**Comment by D-X-Y** [comment]
> Thank you, and will this part of the code be shared later?

Yes, this part of codes will be shared upon the acceptance of our following work.

**Comment by sebwal** [comment]
Any update on this?

**Comment by D-X-Y** [comment]
@sebwal , Please see the instructions at here https://github.com/D-X-Y/NAS-Projects#searching-on-the-nasnet-search-space
You can use GDAS to search on the DARTS search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/GDAS-search-NASNet-space.sh cifar10 1 -1
```
or on the NAS-bench-102 search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/algos/GDAS.sh     cifar10 -1
```

**Comment by D-X-Y** [comment]
@SuSuXia , all searching codes are released in the up-to-date version of this repo. Sorry for the inconvenience.
