### ISSUE TITLE
What's the difference from SNAS?

### ISSUE THREAD

**Issue by JunrQ** [D-X-Y/GDAS#22]
Can you point out the differences between GDAS and [SNAS](https://arxiv.org/abs/1812.09926)?

Thanks.

**Comment by D-X-Y** [comment]
GDAS (CVPR submission is 2018.11.16) and SNAS (available at arxiv on 2018.12.09) are concurrent work as indicated in our paper (last paragraph in Sec-2). Regarding the technical details, we are similar, while GDAS additionally proposed an acceleration trick ("Acceleration" on Page 5).
