### ISSUE TITLE
What's the usage 'index' in genotypes?

### ISSUE THREAD

**Issue by YANGWAGN** [D-X-Y/GDAS#23]
In the genotype of GDAS_GF. There are three items for one op in a cell, which are (op, index, value).
For example
('skip_connect', 0, 0.13017432391643524)

What's the usage for the 'index'? Thanks.

**Comment by YANGWAGN** [comment]
Thank you for your sharing, I think that  I have known how it works.

**Comment by D-X-Y** [comment]
Cool! the index indicates the index of the input node.
