### ISSUE TITLE
Some doubts about the architecture sampling

### ISSUE THREAD

**Issue by liuzili97** [D-X-Y/GDAS#25]
Hi, thanks for your great work. After reading your paper, I have some doubts.
1. 1 or n architectures are sampled when using n GPUs for searching?
2. The o_k sampled from Gumbel(0,1) has a range of known values, but the A^k_{i,h} may vary a lot when adapting different wd. So what's the best range for A?

Thanks.

**Comment by D-X-Y** [comment]
Thanks for your interest.
1, n architectures for n GPUs
2, good point. It could be a problem. We initialize A with Gaussin(0, 0.001) and do not constrain it during searching.

**Comment by liuzili97** [comment]
thanks!
