### ISSUE TITLE
Question about NAS Acceleration

### ISSUE THREAD

**Issue by yanwei-li** [D-X-Y/GDAS#4]
Hi! Thanks for your good job!

I have some questions about the Fast Acceleration version. In the main paper, it is said to adopt Gumbel Softmax with temperature to relax argmax function during the searching process. But in "model_search.py", I found it using the normal version which calculates all ops' probs (same with that in DARTS).

Is it something wrong or just my fault?

**Comment by D-X-Y** [comment]
@yanwei-li  Thanks for your interest.
`model_search.py` is the compared algorithm （DARTS first order）of our GDAS. We did not include our searching model in this repo.
