### ISSUE TITLE
Custom training data

### ISSUE THREAD

**Issue by deepseek** [D-X-Y/GDAS#7]
@D-X-Y thank you for your hard work

How can I train on my own dataset, with a simple structure of:
- input original images
- input mask images

**Comment by D-X-Y** [comment]
I define the dataset and data augmentation function in https://github.com/D-X-Y/GDAS/blob/master/lib/datasets/get_dataset_with_transform.py#L38 . You can add your own dataset in this function.

**Comment by D-X-Y** [comment]
Feel free to reopen it as necessary.
