### ISSUE TITLE
How to show the network structure?

### ISSUE THREAD

**Issue by duoduoda** [D-X-Y/GDAS#8]
Thanks for your work.

I have trained the cifar10 by GDAS_F1，I want to know the network structure which I get by searching. How can I get it?

thank you.

**Comment by D-X-Y** [comment]
Thanks for your interest. GDAS_F1 is our searched model, to visualize it you can use this python code : `https://github.com/D-X-Y/GDAS/blob/master/exps-cnn/cvpr-vis.py`. This repo does not include the searching code, more details are explained in https://github.com/D-X-Y/GDAS/issues/5

Best Regards,

**Comment by duoduoda** [comment]
Thank you for your reply.

So, the cell and network are your searched model? and this code do not combine the searching of cell and network?

**Comment by D-X-Y** [comment]
Yes,  this code does not include the searching procedure. The released cell is searched by GDAS, and the network (macro-structure) during searching is similar to the one during training. We only search for the cell and the network structure is pre-defined.
