### ISSUE TITLE
how do I search from scratch?

### ISSUE THREAD

**Issue by siddikui** [D-X-Y/GDAS#9]
That's a very nice paper and thanks for the repo. Training scripts on searched architectures just worked, however, I have been unable to figure out which scripts to use to search the cells from scratch. Thank you.

**Comment by D-X-Y** [comment]
Sorry for the inconvenience. Since our extension version is under review, we can not release the searching code right now. If you have any questions w.r.t. the searching procedure, I'm glad to help solve your problems.

**Comment by MarioProjects** [comment]
Still under review? Could you share more info? Thanks

**Comment by D-X-Y** [comment]
@MarioProjects  Journal papers usually need more than 6 months for the first round of review. Sorry about that.
If you have any questions, would you mind to open an issue or directly email me? I'm willing to help solve your questions.

**Comment by D-X-Y** [comment]
@siddikui @MarioProjects Sorry for the inconvenience.
Please see the instructions at here https://github.com/D-X-Y/NAS-Projects#searching-on-the-nasnet-search-space
You can use GDAS to search on the DARTS search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/GDAS-search-NASNet-space.sh cifar10 1 -1
```
or on the NAS-bench-102 search space by:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/algos/GDAS.sh     cifar10 -1
```
